var albums = new Map();
albums.set("1", {titre: "Croc vert", numero: "23", idSerie: "6", idAuteur: "13", prix: "24.50", idExemplaire: "1", nbExpl:"3"});
albums.set("2", {titre: "Machine qui rêve", numero: "46", idSerie: "2", idAuteur: "14", prix: "23.50" , idExemplaire: "2", nbExpl:"1"});
albums.set("3", {titre: "La guerre des gloutons (II)", numero: "13", idSerie: "16", idAuteur: "11", prix: "14.50" , idExemplaire: "3", nbExpl:"3"});
albums.set("4", {titre: "Le jour du Mayflower", numero: "20", idSerie: "10", idAuteur: "16", prix: "12" , idExemplaire: "4", nbExpl:"2"});
albums.set("6", {titre: "La griffe de Rome", numero: "03", idSerie: "17", idAuteur: "9", prix: "14.50" , idExemplaire: "5", nbExpl:"3"});
albums.set("7", {titre: "Le Waltras", numero: "07", idSerie: "13", idAuteur: "8", prix: "15.20" , idExemplaire: "6", nbExpl:"3"});
albums.set("8", {titre: "Le sang des comètes", numero: "08", idSerie: "18", idAuteur: "10", prix: "14.50" , idExemplaire: "7", nbExpl:"2"});
albums.set("9", {titre: "La bête fabuleuse", numero: "08", idSerie: "9", idAuteur: "10", prix: "14.50" , idExemplaire: "8", nbExpl:"3"});
albums.set("10", {titre: "(Avant la quête) L'ami Javin", numero: "A01", idSerie: "22", idAuteur: "18", prix: "14.10", idExemplaire: "9", nbExpl:"5"});
albums.set("11", {titre: "Le sens de la vie", numero: "12", idSerie: "23", idAuteur: "19", prix: "10.50", idExemplaire: "10", nbExpl:"3"});
albums.set("13", {titre: "Mes meilleurs copains", numero: "11", idSerie: "23", idAuteur: "19", prix: "11", idExemplaire: "11", nbExpl:"3"});
albums.set("15", {titre: "Nadia se marie", numero: "10", idSerie: "23", idAuteur: "19", prix: "12.50", idExemplaire: "12", nbExpl:"5"});
albums.set("18", {titre: "La loi du préau", numero: "09", idSerie: "23", idAuteur: "19", prix: "10.50", idExemplaire: "13", nbExpl:"2"});
albums.set("19", {titre: "Gare aux garous", numero: "03", idSerie: "24", idAuteur: "20", prix: "11.40", idExemplaire: "14", nbExpl:"3"});
albums.set("20", {titre: "Le Walou Walou ancestral", numero: "02", idSerie: "24", idAuteur: "20", prix: "13.90", idExemplaire: "15", nbExpl:"3"});
albums.set("21", {titre: "Les runes de Gartagueul", numero: "01", idSerie: "24", idAuteur: "20", prix: "14.20", idExemplaire: "16", nbExpl:"1"});
albums.set("22", {titre: "Le temple de Boavista", numero: "08", idSerie: "6", idAuteur: "21", prix: "10.95", idExemplaire: "17", nbExpl:"3"});
albums.set("23", {titre: "L'or de Boavista", numero: "07", idSerie: "6", idAuteur: "21", prix: "12", idExemplaire: "18", nbExpl:"3"});
albums.set("24", {titre: "Fordlandia", numero: "06", idSerie: "6", idAuteur: "21", prix: "9.98", idExemplaire: "19", nbExpl:"1"});
albums.set("25", {titre: "Baby Prinz", numero: "05", idSerie: "6", idAuteur: "21", prix: "11", idExemplaire: "20", nbExpl:"3"});
albums.set("26", {titre: "Le pollen du monte Urticando", numero: "04", idSerie: "6", idAuteur: "21", prix: "10.25", idExemplaire: "21", nbExpl:"3"});
albums.set("27", {titre: "Mars le noir", numero: "03", idSerie: "6", idAuteur: "21", prix: "12.20", idExemplaire: "22", nbExpl:"3"});
albums.set("28", {titre: "Le bébé du bout du monde", numero: "02", idSerie: "6", idAuteur: "22", prix: "11.33", idExemplaire: "23", nbExpl:"2"});
albums.set("29", {titre: "La queue du Marsupilami", numero: "01", idSerie: "6", idAuteur: "22", prix: "10.47", idExemplaire: "24", nbExpl:"3"});
albums.set("30", {titre: "Capturez un Marsupilami !", numero: "00", idSerie: "6", idAuteur: "23", prix: "10.54", idExemplaire: "25", nbExpl:"3"});
albums.set("31", {titre: "Le rayon noir", numero: "44", idSerie: "2", idAuteur: "14", prix: "9.98", idExemplaire: "26", nbExpl:"1"});
albums.set("32", {titre: "Luna fatale", numero: "45", idSerie: "2", idAuteur: "14", prix: "10.00", idExemplaire: "27", nbExpl:"3"});
albums.set("33", {titre: "A Moscou", numero: "42", idSerie: "2", idAuteur: "14", prix: "10.95", idExemplaire: "28", nbExpl:"2"});
albums.set("34", {titre: "Vito la déveine", numero: "43", idSerie: "2", idAuteur: "14", prix: "10.42", idExemplaire: "29", nbExpl:"1"});
